name: 'Test workflow to see if auto deploying refreshed WP instances works'

on:
    workflow_dispatch:
    # Deploy the nightly version of WordPress every day at 8am UTC
    schedule:
        - cron: '*/5 * * * *'

jobs:
    build_and_deploy:
        # Only run this workflow from the trunk branch and when it's triggered by dmsnell OR adamziel
        if: >
            github.ref == 'refs/heads/trunk' && (
                github.actor == 'adamziel' ||
                github.actor == 'dmsnell' ||
                github.actor == 'bgrgicak'
            )

        runs-on: ubuntu-latest
        environment:
            name: wordpress-assets
        steps:
            - name: Deploy website
              uses: benc-uk/workflow-dispatch@v1
              with:
                  workflow: build-website.yml
                  token: ${{ secrets.GITHUB_TOKEN }}
